## Proactive Disclosure - Travel Expenses - Proactive Disclosure - Travel Expenses

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#load data
data = pd.read_csv(r'./data/travel expense.csv')
print(data.shape)
data.head()

(88305, 21)

,ref_number,disclosure_group,title_en,title_fr,name,purpose_en,purpose_fr,start_date,end_date,destination_en,...,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,additional_comments_fr,owner_org,owner_org_title
0,T-20120-P11-001,SLE,Chief Executive Officer,Président directeur-général,Philip Rizcallah,To attend meeting with Saskatchewan Provincial...,Pour assister à une réunion avec le gouverneme...,2020-02-03,2020-02-04,"Regina, Saskatchewan, Canada",...,646.17,117.26,157.78,197.25,0.0,1118.46,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes d’acce...
1,T-2020-P11-0001,SLE,Chair,Président,"Bérubé, Paul-Claude",Board members meeting,Réunion du conseil,2020-02-09,2020-02-13,"Vancouver, British Columbia, Canada",...,1104.27,189.72,841.31,461.84,NaN,2597.14,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes d’acce...
2,T-2020-P11-0002,SLE,Vice Chair,vice-présidente,"Reid, Mary",Board members meeting,Réunion du conseil,2020-02-09,2020-02-14,"Vancouver, British Columbia, Canada",...,2511.31,132.48,785.65,591.00,108.3,4128.74,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes d’acce...
3,T-2020-P11-0003,SLE,Board Of Directors,Membre du conseil de direction,"McLaughlin, Joseph",Board members meeting,Réunion du conseil,2020-02-09,2020-02-12,"Vancouver, British Columbia, Canada",...,NaN,58.32,630.99,264.60,123.0,1076.91,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes d’acce...
4,T-2020-P11-0004,SLE,Board Of Directors,Membre du conseil de direction,"Haan, Maureen",Board members meeting,Réunion du conseil,2020-02-09,2020-02-12,"Vancouver, British Columbia, Canada",...,880.99,192.76,630.99,332.45,NaN,2037.19,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes d’acce...

When we see the sample data, we can see there are some columns that's duplicate with different language. So we will remove French's column.

In [3]:
data.columns

Index(['ref_number', 'disclosure_group', 'title_en', 'title_fr', 'name',
       'purpose_en', 'purpose_fr', 'start_date', 'end_date', 'destination_en',
       'destination_fr', 'airfare', 'other_transport', 'lodging', 'meals',
       'other_expenses', 'total', 'additional_comments_en',
       'additional_comments_fr', 'owner_org', 'owner_org_title'],
      dtype='object')

In [4]:
#remove french column
french = ['title_fr', 'purpose_fr', 'destination_fr', 'additional_comments_fr']
data.drop(french, axis=1, inplace=True)
data.shape

(88305, 17)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88305 entries, 0 to 88304
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ref_number              88304 non-null  object
 1   disclosure_group        66624 non-null  object
 2   title_en                87597 non-null  object
 3   name                    87757 non-null  object
 4   purpose_en              88290 non-null  object
 5   start_date              88305 non-null  object
 6   end_date                87501 non-null  object
 7   destination_en          87668 non-null  object
 8   airfare                 84538 non-null  float64
 9   other_transport         86217 non-null  float64
 10  lodging                 85845 non-null  float64
 11  meals                   87105 non-null  float64
 12  other_expenses          80054 non-null  float64
 13  total                   88116 non-null  float64
 14  additional_comments_en  10999 non-null  object
 15  owner_org               88305 non-null  object
 16  owner_org_title         88305 non-null  object
dtypes: float64(6), object(11)
memory usage: 11.5+ MB

In [6]:
#check for null value
data.isnull().sum()

ref_number                    1
disclosure_group          21681
title_en                    708
name                        548
purpose_en                   15
start_date                    0
end_date                    804
destination_en              637
airfare                    3767
other_transport            2088
lodging                    2460
meals                      1200
other_expenses             8251
total                       189
additional_comments_en    77306
owner_org                     0
owner_org_title               0
dtype: int64

We will be replacing numerical data that contain null with 0 then we will investigate the other columns.

In [7]:
#replace null with 0
num_null = ['airfare', 'other_transport', 'lodging', 'meals', 'other_expenses', 'total']
for x in num_null:
    data[x].fillna(0, inplace=True)
data.isnull().sum()

ref_number                    1
disclosure_group          21681
title_en                    708
name                        548
purpose_en                   15
start_date                    0
end_date                    804
destination_en              637
airfare                       0
other_transport               0
lodging                       0
meals                         0
other_expenses                0
total                         0
additional_comments_en    77306
owner_org                     0
owner_org_title               0
dtype: int64

The next thing that we will do is handling the null value of string data. We will convert all of them to lower case to make it uniform first and check for the unique value.

In [8]:
for x in data:
    if data[x].dtypes == object:
        data[x] = data[x].str.lower()

data.head()

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
0,t-20120-p11-001,sle,chief executive officer,philip rizcallah,to attend meeting with saskatchewan provincial...,2020-02-03,2020-02-04,"regina, saskatchewan, canada",646.17,117.26,157.78,197.25,0.0,1118.46,NaN,casdo-ocena,accessibility standards canada | normes d’acce...
1,t-2020-p11-0001,sle,chair,"bérubé, paul-claude",board members meeting,2020-02-09,2020-02-13,"vancouver, british columbia, canada",1104.27,189.72,841.31,461.84,0.0,2597.14,NaN,casdo-ocena,accessibility standards canada | normes d’acce...
2,t-2020-p11-0002,sle,vice chair,"reid, mary",board members meeting,2020-02-09,2020-02-14,"vancouver, british columbia, canada",2511.31,132.48,785.65,591.00,108.3,4128.74,NaN,casdo-ocena,accessibility standards canada | normes d’acce...
3,t-2020-p11-0003,sle,board of directors,"mclaughlin, joseph",board members meeting,2020-02-09,2020-02-12,"vancouver, british columbia, canada",0.00,58.32,630.99,264.60,123.0,1076.91,NaN,casdo-ocena,accessibility standards canada | normes d’acce...
4,t-2020-p11-0004,sle,board of directors,"haan, maureen",board members meeting,2020-02-09,2020-02-12,"vancouver, british columbia, canada",880.99,192.76,630.99,332.45,0.0,2037.19,NaN,casdo-ocena,accessibility standards canada | normes d’acce...

We will check details with null ref_number to get some insights, and show the data with duplicated reference number.

In [9]:
print(f'Unique reference number: {data.ref_number.nunique()}\nTotal data: {data.shape[0]}')
data[data['ref_number'].duplicated() == True].sort_values('ref_number').head()

Unique reference number: 52654
Total data: 88305

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
73659,101,sle,"vice-president, special initiatives",carol sheedy,"march 2004, accommodation",2004-03-01,2004-03-31,"halifax, nova scotia",0.00,0.00,988.0,0.0,0.00,988.00,NaN,pc,parks canada | parcs canada
73651,102,sle,"vice-president, special initiatives",carol sheedy,"april 2004, accommodation",2004-04-01,2004-04-30,"halifax, nova scotia",0.00,0.00,988.0,0.0,0.00,988.00,NaN,pc,parks canada | parcs canada
73340,103,sle,"vice-president, special initiatives",carol sheedy,"may 2004, accommodation",2004-05-01,2004-05-31,"halifax, nova scotia",0.00,0.00,988.0,0.0,0.00,988.00,NaN,pc,parks canada | parcs canada
73652,104,sle,"director general, west and northern canada",gaby fortin,executive board face to face and classificatio...,2004-03-29,2004-03-31,"gatineau, quebec",3250.21,169.92,0.0,191.7,100.10,3711.93,NaN,pc,parks canada | parcs canada
73650,105,sle,"director general, west and northern canada",gaby fortin,meeting with the department of fisheries and o...,2004-04-13,2004-04-15,"vancouver, bc",682.68,132.00,234.0,193.0,142.41,1384.09,NaN,pc,parks canada | parcs canada

In [10]:
#check sample
data.loc[data['ref_number']=='101']

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
48486,101,NaN,director,horst intscher,to attend egmont discussions regarding locatio...,2007-05-07,2007-05-07,"toronto, ontario",652.17,40.8,0.0,0.0,16.5,709.47,NaN,fintrac-canafe,financial transactions and reports analysis ce...
73659,101,sle,"vice-president, special initiatives",carol sheedy,"march 2004, accommodation",2004-03-01,2004-03-31,"halifax, nova scotia",0.00,0.0,988.0,0.0,0.0,988.00,NaN,pc,parks canada | parcs canada

In [11]:
#show the null data
data[data['ref_number'].isnull()]

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
71777,NaN,sle,"president, pacifican","jones, dylan",global federation of competitiveness councils ...,2022-11-11,2022-11-17,"athens, greece",7490.86,262.39,1910.31,1060.47,60.36,10784.39,missing internal reference number - 8950,pacifican,pacific economic development canada | développ...

While we check the data, on additional_comments_en it shows 'missing internal reference number - 8950'. Since there is an information about the reference number in the additional comments, we will try to find if there is any data with reference number contains 8905

In [12]:
#find data with reference 8905
data.loc[data['ref_number'].isin(['8950'])]

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
72082,8950,sle,"vice-president, special initiatives",carol sheedy,meeting with the never forgotten national memo...,2014-12-22,2014-12-22,"toronto, ontario",398.18,243.69,0.0,32.1,0.0,673.97,NaN,pc,parks canada | parcs canada

In [13]:
data['ref_number'].fillna(8905, inplace=True)
data.isnull().sum()

ref_number                    0
disclosure_group          21681
title_en                    708
name                        548
purpose_en                   15
start_date                    0
end_date                    804
destination_en              637
airfare                       0
other_transport               0
lodging                       0
meals                         0
other_expenses                0
total                         0
additional_comments_en    77306
owner_org                     0
owner_org_title               0
dtype: int64

In [14]:
for x in data:
    if data[x].isnull().sum()>0:
        print(f'{data[x].unique()} - {data[x].nunique()}')

['sle' nan 'mpses' 'fovc'] - 3
['chief executive officer' 'chair' 'vice chair' ...
 'executive committee member' 'executive director - yesab'
 'chair of yesa board'] - 3901
['philip rizcallah' 'bérubé, paul-claude' 'reid, mary' ...
 'dennis, nicloux' 'dennis nicloux' 'bryony mcintyre'] - 6208
['to attend meeting with saskatchewan provincial government'
 'board members meeting'
 'meeting with chief executive officer of accessibility stadards canada'
 ... 'placer mining tour' 'pan territorial board forrm attendance'
 'meeting with vuntut gwitchin first nation'] - 53212
['2020-02-04' '2020-02-13' '2020-02-14' ... '2013-11-03' '2015-09-07'
 '2021-05-13'] - 6690
['regina, saskatchewan, canada' 'vancouver, british columbia, canada'
 'montreal, quebec, canada' ...
 'haines junction, rainbow lake, quill creek'
 'watson lake and teslin, yukon' 'mayo, yukon'] - 15155
[nan 'trip was cancelled' 'parking fees reimbursed for  various dates' ...
 'to extend flight pass ' 'airfare booked using flight pass'
 'helicoper of total $3,381.00 was provided for 4 persons (3 board members and 1 staff)'] - 5435

In [15]:
#replace to unknown
unknown_col = ['disclosure_group', 'title_en', 'name', 'additional_comments_en', 'purpose_en', 'destination_en']
for x in unknown_col:
    data[x].fillna('unknown', inplace=True)
data.isnull().sum()

ref_number                  0
disclosure_group            0
title_en                    0
name                        0
purpose_en                  0
start_date                  0
end_date                  804
destination_en              0
airfare                     0
other_transport             0
lodging                     0
meals                       0
other_expenses              0
total                       0
additional_comments_en      0
owner_org                   0
owner_org_title             0
dtype: int64

In [16]:
#check data sample with null end date
data[data['end_date'].isnull()].head()

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
6413,t-2006-q1-00033,unknown,president,michelle d'auray,various meetings,2006-03-06,NaN,ottawa,0.00,0.00,0.0,45.5,0.0,45.50,unknown,ced-dec,canada economic development for quebec regions...
6521,t-2006-q2-00013,unknown,president,michelle d'auray,various meetings,2006-08-16,NaN,toronto,819.23,126.00,0.0,33.6,0.0,978.83,unknown,ced-dec,canada economic development for quebec regions...
6635,t-2005-q3-00071,unknown,president,michelle d'auray,selection board,2005-11-25,NaN,ottawa,0.00,0.00,0.0,24.2,0.0,24.20,unknown,ced-dec,canada economic development for quebec regions...
6637,t-2006-q1-00032,unknown,president,michelle d'auray,various meetings,2006-04-07,NaN,ottawa,0.00,0.00,0.0,46.1,0.0,46.10,unknown,ced-dec,canada economic development for quebec regions...
8125,t-2006-q2-00030,unknown,"vice-president, policy and planning (acting)",rita tremblay,meeting with the president of canada economic ...,2006-07-04,NaN,montréal,0.00,221.44,0.0,0.0,0.0,221.44,unknown,ced-dec,canada economic development for quebec regions...

Since we don't have any information regarding the null end date, we will be replacing it with the start-date

In [17]:
#fill null end date with start date
data['end_date'].fillna(data['start_date'], inplace=True)
data.loc[data['ref_number']=='t-2006-q1-00033']

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title
6413,t-2006-q1-00033,unknown,president,michelle d'auray,various meetings,2006-03-06,2006-03-06,ottawa,0.00,0.0,0.00,45.5,0.0,45.50,unknown,ced-dec,canada economic development for quebec regions...
15949,t-2006-q1-00033,unknown,press secretary,véronique bruneau,banff world television festival,2006-06-10,2006-06-12,banff,2879.74,0.0,525.79,168.1,0.0,3573.63,unknown,pch,canadian heritage | patrimoine canadien
34113,t-2006-q1-00033,sle,senior associate deputy minister,hy braiter,meeting - service canada management board,2006-05-02,2006-05-05,"vancouver, british columbia, canada",2835.54,74.4,666.90,127.8,0.0,3704.64,unknown,esdc-edsc,employment and social development canada | emp...

For the destination, we will be split the data by its countries. We will check if the data contains countries list then move that to the new column 'country'.

In [18]:
countries_list = pd.read_csv(r'./data/countries_britanica.csv', header=None)
print(countries_list.shape)
countries_list.head()

(197, 1)

             0
0  afghanistan
1      albania
2      algeria
3      andorra
4       angola

In [19]:
c_pattern = '|'.join(str(x) for x in countries_list[0])
c_pattern

'afghanistan|albania|algeria|andorra|angola|antigua and barbuda|argentina|armenia|australia|austria|azerbaijan|the bahamas|bahrain|bangladesh|barbados|belarus|belgium|belize|benin|bhutan|bolivia|bosnia and herzegovina|botswana|brazil|brunei|bulgaria|burkina faso|burundi|cabo verde|cambodia|cameroon|canada|central african republic|chad|chile|china|colombia|comoros|democratic republic of the congo|republic of the congo|costa rica|côte d’ivoire|croatia|cuba|cyprus|czech republic|denmark|djibouti|dominica|dominican republic|east timor|timor|ecuador|egypt|el salvador|equatorial guinea|eritrea|estonia|eswatini|ethiopia|fiji|finland|france|gabon|the gambia|georgia|germany|ghana|greece|grenada|guatemala|guinea|guinea-bissau|guyana|haiti|honduras|hungary|iceland|india|indonesia|iran|iraq|ireland|israel|italy|jamaica|japan|jordan|kazakhstan|kenya|kiribati|north korea|south korea|kosovo|kuwait|kyrgyzstan|laos|latvia|lebanon|lesotho|liberia|libya|liechtenstein|lithuania|luxembourg|madagascar|malawi|malaysia|maldives|mali|malta|marshall islands|mauritania|mauritius|mexico|micronesia|moldova|monaco|mongolia|montenegro|morocco|mozambique|myanmar|burma|namibia|nauru|nepal|netherlands|new zealand|nicaragua|niger|nigeria|north macedonia|norway|oman|pakistan|palau|panama|papua new guinea|paraguay|peru|philippines|poland|portugal|qatar|romania|russia|rwanda|saint kitts and nevis|saint lucia|saint vincent and the grenadines|samoa|san marino|sao tome and principe|saudi arabia|senegal|serbia|seychelles|sierra leone|singapore|slovakia|slovenia|solomon islands|somalia|south africa|spain|sri lanka|sudan|suriname|sweden|switzerland|syria|taiwan|tajikistan|tanzania|thailand|togo|tonga|trinidad and tobago|tunisia|turkey|turkmenistan|tuvalu|uganda|ukraine|united arab emirates|united kingdom|united states|uruguay|uzbekistan|vanuatu|vatican city|venezuela|vietnam|yemen|zambia|zimbabwe'

In [20]:
import re
def pattern_searcher(search_str:str, search_list:str):

    search_obj = re.search(search_list, search_str)
    if search_obj :
        return_str = search_str[search_obj.start(): search_obj.end()]
    else:
        return_str = 'unknown'
    return return_str

In [21]:
data['country'] = data['destination_en'].apply(lambda x: pattern_searcher(search_str=x, search_list=c_pattern))
data.head()

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title,country
0,t-20120-p11-001,sle,chief executive officer,philip rizcallah,to attend meeting with saskatchewan provincial...,2020-02-03,2020-02-04,"regina, saskatchewan, canada",646.17,117.26,157.78,197.25,0.0,1118.46,unknown,casdo-ocena,accessibility standards canada | normes d’acce...,canada
1,t-2020-p11-0001,sle,chair,"bérubé, paul-claude",board members meeting,2020-02-09,2020-02-13,"vancouver, british columbia, canada",1104.27,189.72,841.31,461.84,0.0,2597.14,unknown,casdo-ocena,accessibility standards canada | normes d’acce...,canada
2,t-2020-p11-0002,sle,vice chair,"reid, mary",board members meeting,2020-02-09,2020-02-14,"vancouver, british columbia, canada",2511.31,132.48,785.65,591.00,108.3,4128.74,unknown,casdo-ocena,accessibility standards canada | normes d’acce...,canada
3,t-2020-p11-0003,sle,board of directors,"mclaughlin, joseph",board members meeting,2020-02-09,2020-02-12,"vancouver, british columbia, canada",0.00,58.32,630.99,264.60,123.0,1076.91,unknown,casdo-ocena,accessibility standards canada | normes d’acce...,canada
4,t-2020-p11-0004,sle,board of directors,"haan, maureen",board members meeting,2020-02-09,2020-02-12,"vancouver, british columbia, canada",880.99,192.76,630.99,332.45,0.0,2037.19,unknown,casdo-ocena,accessibility standards canada | normes d’acce...,canada

data.loc[data['total']<0]

total = data['total'].unique()
sorted(total)

We will be leaving the destination only country level for now. Next, we will be exporting the data as excel file and create a dashboard using Tableau

In [22]:
data.loc[data['start_date']=='2020-01-01'].head()

,ref_number,disclosure_group,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,owner_org,owner_org_title,country
18818,t-2020-p10-00008,unknown,"assistant deputy minister, citizenship, herita...","slowey, charles",petty cash,2020-01-01,2020-01-31,national capital region,0.0,0.0,0.0,0.0,13.0,13.0,unknown,pch,canadian heritage | patrimoine canadien,unknown
18819,t-2020-p10-00009,unknown,"assistant deputy minister, official languages,...","welbourne, maia",no expense to report,2020-01-01,2020-01-31,unknown,0.0,0.0,0.0,0.0,0.0,0.0,unknown,pch,canadian heritage | patrimoine canadien,unknown
18824,t-2020-p10-00014,unknown,minister of canadian heritage,"guilbeault, steven",no expense to report,2020-01-01,2020-01-31,unknown,0.0,0.0,0.0,0.0,0.0,0.0,unknown,pch,canadian heritage | patrimoine canadien,unknown
18827,t-2020-p10-00017,unknown,special assistant,"browne, maria",no expense to report,2020-01-01,2020-01-31,unknown,0.0,0.0,0.0,0.0,0.0,0.0,unknown,pch,canadian heritage | patrimoine canadien,unknown
18830,t-2020-p10-00020,unknown,policy advisor,"cheung, irene",no expense to report,2020-01-01,2020-01-31,unknown,0.0,0.0,0.0,0.0,0.0,0.0,unknown,pch,canadian heritage | patrimoine canadien,unknown

data.to_csv(r'./data/travel_clean.csv', index=False)

## Cluster the travel purpose using BERTopic
not perform that well

In [1]:
import pandas as pd

data = pd.read_csv(r'.\data\travel_clean.csv')

In [2]:
#import library
from bertopic import BERTopic

c:\Users\dvnbi\Documents\NLP Sentiment\nlp\lib\site-packages\umap\distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
c:\Users\dvnbi\Documents\NLP Sentiment\nlp\lib\site-packages\umap\distances.py:1071: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
c:\Users\dvnbi\Documents\NLP Sentiment\nlp\lib\site-packages\umap\distances.py:1086: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()
c:\Users\dvnbi\Documents\NLP Sentiment\nlp\lib\site-packages\umap\umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit()

data['purpose_en'][0]

In [3]:
bert_purpose = BERTopic(language='English', calculate_probabilities=False, embedding_model='all-MiniLM-L6-v2')

test = data['purpose_en'][0]
test

x, prob = bert_purpose.fit_transform('to attend meeting with saskatchewan provincial government')
bert_purpose.get_topic()

In [4]:
purpose, probs = bert_purpose.fit_transform(data['purpose_en'])

In [6]:
bert_purpose.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,16005,-1_first_nation_atlantic_as,"[first, nation, atlantic, as, alberta, british...",[to attend various meetings: operations and po...
1,0,1776,0_various_meetings_current_issues,"[various, meetings, current, issues, colleague...","[various meetings, various meetings, various m..."
2,1,877,1_attend_meetings_eleven_delegates,"[attend, meetings, eleven, delegates, india, s...","[attend meetings, attend meetings, attend meet..."
3,2,555,2_accompany_assigned_lévis_minister,"[accompany, assigned, lévis, minister, annouce...","[accompany the minister, accompany the ministe..."
4,3,364,3_aboriginal_indigenous_circle_peoples,"[aboriginal, indigenous, circle, peoples, cons...",[to attend the aboriginal economic development...
...,...,...,...,...,...
2052,2051,10,2051_territorial_accompanied_provincial_supported,"[territorial, accompanied, provincial, support...",[accompanied the minister to the federal-provi...
2053,2052,10,2052_retirement_income_irpp_adjustment,"[retirement, income, irpp, adjustment, pre, wo...","[retirement planning session, pre-retirement c..."
2054,2053,10,2053_negotiation_face_negotiations_compensation,"[negotiation, face, negotiations, compensation...",[compensation - face to face negotiation sessi...
2055,2054,10,2054_agricoles_producteurs_des_congrès,"[agricoles, producteurs, des, congrès, framboi...",[to support the minister to participate in the...
2056,2055,10,2055_mitacs_multiple_pipeline_other,"[mitacs, multiple, pipeline, other, key, talen...",[to attend multiple ministerial announcements ...

In [8]:
bert_purpose.get_topic(0)

[('various', 0.03187206491938906),
 ('meetings', 0.0068512529837132935),
 ('current', 0.0007298625029288794),
 ('issues', 0.0006949715592440693),
 ('colleagues', 0.000502456385089191),
 ('series', 0.00041409938939656753),
 ('headquarters', 0.0002009570149988646),
 ('on', 6.675077283737025e-05),
 ('meeting', 2.2262644156467287e-05),
 ('for', 1.0612218622883893e-05)]

## topic modeling LDA

In [ ]:
purpose_dtm = data['purpose_en']